SELECT * FROM PAYMENT WHERE type_id = (SELECT id from PAYMENTTYPE WHERE name='MONTHLY');
SELECT * FROM MARK WHERE subject_id = (SELECT id from SUBJECT WHERE name = 'Art');
SELECT DISTINCT * FROM STUDENT INNER JOIN PAYMENT ON STUDENT.id = PAYMENT.student_id WHERE PAYMENT.type_id = (SELECT id FROM PAYMENTTYPE WHERE name = 'WEEKLY');
SELECT * FROM STUDENT INNER JOIN MARK ON STUDENT.id = MARK.student_id JOIN SUBJECT ON SUBJECT.id = MARK.subject_id WHERE mark is not null and SUBJECT.name = 'Math';
