SELECT MIN(birhday) FROM STUDENT;
SELECT MIN(payment_date) FROM PAYMENT;
SELECT AVG(mark) FROM MARK HAVING subject_id = (SELECT id FROM SUBJECT WHERE name = 'Math');
SELECT MIN(amount) FROM PAYMENT HAVING type_id = (SELECT id FROM PAYMENTTYPE name = 'WEEKLY');